config/routes.rb
Rails.application.routes.draw do
  # read all
  get 'tasks', to: 'tasks#index', as: 'tasks'
  # read one
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  # CREATE
  get 'new', to: 'tasks#new', as: 'tasks_new'

  post 'tasks', to: 'tasks#create'
  # update
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'tasks_edit'

  patch 'tasks/:id', to: 'tasks#update'
  # destroy
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
validates :title, presence: true
validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <div class="form-container text-center">
    <%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "label"%>
      <%= f.text_field :title, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_area :details, class: "form-control"%>
    <% unless @task.id.nil? %>
        <%=  f.check_box :completed, {checked: false}, true, false %>
        <%= f.label "mark as done" %>
    <% end %>
      </div>
    <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="wrapper-black">
  <div class="container text-center">
      <% @tasks.each do |task|  %>
    <div class="card text-left">
        <div class="card-status"><% if task.completed == false %>
          <i class="far fa-square"></i>
          <% end %>
          <%if task.completed == true %>
          <i class="far fa-check-square"></i>
          <% end %></div>
       <div class="card-title"> <%=link_to task.title, task_path(task.id) %></div>
        <div class="card-delete"><%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } %></div>
    </div>
      <% end %>
    <%= link_to "Create a new task", tasks_new_path, class: 'btn btn-primary btn-lg' %>
    </div>
</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="container text-center">
  <div class="task-detail"><h1><%= @task.title %></h1>
    <div class="task-text-area">
      <h3><%= @task.details %></h3>
    </div>
    <p>Status: <%=@task.completed ? "Done" : "Undone" %></p>

    <%= link_to "Edit this task", tasks_edit_path, class: 'btn btn-info' %>
    <%= link_to "Delete this task", task_path(@task), class: 'btn btn-danger' ,
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    <%= link_to "Back to all", tasks_path, class: 'btn btn-success'  %></div>
</div>